site_name: Flexcyon Theme Docs
site_url: https://bladeacer.github.io/flexcyon
repo_url: https://github.com/bladeacer/flexcyon
repo_name: bladeacer/flexcyon
copyright: >
  Copyright &copy; bladeacer 2025
plugins:
  - search
  - tags
  - meta
  - git-revision-date-localized:
      enable_creation_date: true
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: material/github
    logo: material/file-document

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.instant.preview
    - navigation.path
    - navigation.instant
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - content.action.view
    - content.code.cojy
  markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - footnotes

  extra:
    tags:
      Style Settings: style_settings
      README: readme
      Logs: logs
      Plugins: plugins
      Snippets: snippets
      Styling: styling
      Callouts: callouts
  nav:
    - README:
      - README/index.md
      - README/license.md
    - Styling:
      - styling/index.md
      - Style Settings:
        - styling/Style-Settings/index.md
      - Callout Metadata:
        - styling/Callout-Metadata/index.md
        - styling/Callout-Metadata/flashcard.md
        - styling/Callout-Metadata/popup.md
        - Icon Styling:
          - styling/Callout-Metadata/icon-styling/index.md
        - Title Styling:
          - styling/Callout-Metadata/title-styling/index.md
          - styling/Callout-Metadata/title-styling/page-1.md
          - styling/Callout-Metadata/title-styling/page-2.md
          - styling/Callout-Metadata/title-styling/page-3.md
          - styling/Callout-Metadata/title-styling/page-4.md
          - styling/Callout-Metadata/title-styling/page-5.md
          - styling/Callout-Metadata/title-styling/page-6.md
          - styling/Callout-Metadata/title-styling/page-7.md
          - styling/Callout-Metadata/title-styling/page-8.md
          - styling/Callout-Metadata/title-styling/page-9.md
          - styling/Callout-Metadata/title-styling/page-10.md
          - styling/Callout-Metadata/title-styling/page-11.md
          - styling/Callout-Metadata/title-styling/page-12.md
          - styling/Callout-Metadata/title-styling/page-13.md
          - styling/Callout-Metadata/title-styling/page-14.md
          - styling/Callout-Metadata/title-styling/page-15.md
          - styling/Callout-Metadata/title-styling/page-16.md
          - styling/Callout-Metadata/title-styling/page-17.md
          - styling/Callout-Metadata/title-styling/page-18.md
          - styling/Callout-Metadata/title-styling/page-19.md
          - styling/Callout-Metadata/title-styling/page-20.md
          - styling/Callout-Metadata/title-styling/page-21.md
          - styling/Callout-Metadata/title-styling/page-22.md
          - styling/Callout-Metadata/title-styling/page-23.md
          - styling/Callout-Metadata/title-styling/page-24.md
          - styling/Callout-Metadata/title-styling/page-25.md
          - styling/Callout-Metadata/title-styling/page-26.md
          - styling/Callout-Metadata/title-styling/page-27.md
          - styling/Callout-Metadata/title-styling/page-28.md
          - styling/Callout-Metadata/title-styling/page-29.md
          - styling/Callout-Metadata/title-styling/page-30.md
        - Background Styling:
          - styling/Callout-Metadata/bg-styling/index.md
        - List Styling:
          - styling/Callout-Metadata/list-styling/index.md
        - Content Styling:
          - styling/Callout-Metadata/content-styling/index.md
          - styling/Callout-Metadata/content-styling/page-1.md
          - styling/Callout-Metadata/content-styling/page-2.md
          - styling/Callout-Metadata/content-styling/page-3.md
          - styling/Callout-Metadata/content-styling/page-4.md
          - styling/Callout-Metadata/content-styling/page-5.md
          - styling/Callout-Metadata/content-styling/page-6.md
          - styling/Callout-Metadata/content-styling/page-7.md
          - styling/Callout-Metadata/content-styling/page-8.md
          - styling/Callout-Metadata/content-styling/page-9.md
          - styling/Callout-Metadata/content-styling/page-10.md
          - styling/Callout-Metadata/content-styling/page-11.md
          - styling/Callout-Metadata/content-styling/page-12.md
          - styling/Callout-Metadata/content-styling/page-13.md
          - styling/Callout-Metadata/content-styling/page-14.md
        - Combined Styling:
          - styling/Callout-Metadata/combined-styling/index.md
          - styling/Callout-Metadata/combined-styling/page-1.md
          - styling/Callout-Metadata/combined-styling/page-2.md
          - styling/Callout-Metadata/combined-styling/page-3.md
          - styling/Callout-Metadata/combined-styling/page-4.md
          - styling/Callout-Metadata/combined-styling/page-5.md
          - styling/Callout-Metadata/combined-styling/page-6.md
          - styling/Callout-Metadata/combined-styling/page-7.md
          - styling/Callout-Metadata/combined-styling/page-8.md
          - styling/Callout-Metadata/combined-styling/page-9.md
          - styling/Callout-Metadata/combined-styling/page-10.md
          - styling/Callout-Metadata/combined-styling/page-11.md
          - styling/Callout-Metadata/combined-styling/page-12.md
          - styling/Callout-Metadata/combined-styling/page-13.md
          - styling/Callout-Metadata/combined-styling/page-14.md
          - styling/Callout-Metadata/combined-styling/page-15.md
          - styling/Callout-Metadata/combined-styling/page-16.md
          - styling/Callout-Metadata/combined-styling/page-17.md
          - styling/Callout-Metadata/combined-styling/page-18.md
          - styling/Callout-Metadata/combined-styling/page-19.md
          - styling/Callout-Metadata/combined-styling/page-20.md
          - styling/Callout-Metadata/combined-styling/page-21.md
          - styling/Callout-Metadata/combined-styling/page-22.md
          - styling/Callout-Metadata/combined-styling/page-23.md
          - styling/Callout-Metadata/combined-styling/page-24.md
        
      - CSS Classes:
        - styling/CSS-Classes/index.md
        - Vertical Alignment:
          - styling/CSS-Classes/vertical-alignment/index.md
        - Editor Background:
          - styling/CSS-Classes/editor-background/index.md
        - Heading Indicators:
          - styling/CSS-Classes/heading-indicators/index.md
    - Credits: 
      - credits/index.md
    - Changelogs: 
      - changelogs/index.md
copyright: "Copyright &copy; bladeacer 2025"
